# Generated by Django 5.0.6 on 2024-05-16 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepositProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.TextField(unique=True)),
                ('kor_co_nm', models.TextField(default=-1)),
                ('fin_prdt_nm', models.TextField(default=-1)),
                ('etc_note', models.TextField(default=-1)),
                ('mtrt_int', models.TextField(default=-1)),
                ('join_deny', models.IntegerField(default=-1)),
                ('join_member', models.TextField(default=-1)),
                ('join_way', models.TextField(default=-1)),
                ('spcl_cnd', models.TextField(default=-1)),
                ('max_limit', models.IntegerField(null=True)),
                ('dcls_strt_day', models.DateField()),
                ('dcls_end_day', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepositOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_co_no', models.TextField()),
                ('fin_prdt_cd', models.TextField()),
                ('intr_rate_type', models.TextField()),
                ('intr_rate_type_nm', models.CharField(max_length=100)),
                ('intr_rate', models.FloatField()),
                ('intr_rate2', models.FloatField()),
                ('save_trm', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deposits.depositproducts')),
            ],
        ),
    ]
